Traceback (most recent call last):
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matteo/anaconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt 

Ttriple=
Ptriple=

T1=np.linspace(100,1,Ttriple)
T2=np.linspace(Ttriple,1,450)

Pv_T=
Po_T=

figure=plt.figure()
axes = figure.add_axes([0.1,0.1,1.,1.])
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

axes.plot(T1,Pv_T,'b-o',label='SLE')
axes.plot(T2,Po_T,'r-^',label='VLE')
axes.plot(Ttriple,Ptriple,'ks',label='Triple Point')


axes.set_xlabel('T, [K]', fontsize=24);
axes.set_ylabel('P [Pa]',fontsize=24); 

axes.legend();

------------------


[0;36m  Cell [0;32mIn[1], line 4[0;36m[0m
[0;31m    Ttriple=[0m
[0m            ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


